# Generated by Django 4.0 on 2022-12-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemvariant',
            unique_together={('name', 'item')},
        ),
    ]
